"""Draw the keymap as ASCII and paste it into README.md.

Reads keymap.c rather than the board, so it works without the keyboard
attached, and keymap.c is what capture-keymap.py and sync-keymap.py keep
matching the board. Writing the drawing by hand would go stale on the first
layout change, so it is generated between markers in the README.

    python render-keymap.py             # print it
    python render-keymap.py --write     # update README.md between the markers
"""

import argparse
import importlib.util
import re
import subprocess
from pathlib import Path

HERE = Path(__file__).parent
KEYMAP_WSL = "/home/nohwnd/p/fiddly/keyboards/fiddly/keymaps/vial/keymap.c"
README_WSL = "/home/nohwnd/p/fiddly/README.md"
START = "<!-- keymap starts here, generated by tools/render-keymap.py -->"
END = "<!-- keymap ends here -->"

LAYER_TITLES = {
    0: "Layer 0, base",
    1: "Layer 1, held with the left thumb",
    2: "Layer 2",
    3: "Layer 3",
}

# Anything not listed falls back to the rules in label().
LABELS = {
    "XXXXXXX": "", "_______": "^", "KC_NO": "", "KC_TRNS": "^",
    "KC_GRV": "`", "KC_MINS": "-", "KC_EQL": "=", "KC_LBRC": "[",
    "KC_RBRC": "]", "KC_SCLN": ";", "KC_QUOT": "'", "KC_BSLS": "\\",
    "KC_COMM": ",", "KC_DOT": ".", "KC_SLSH": "/",
    "KC_TAB": "Tab", "KC_ESC": "Esc", "KC_ENT": "Ent", "KC_ENTER": "Ent",
    "KC_BSPC": "Bspc", "KC_DEL": "Del", "KC_SPACE": "Spc", "KC_SPC": "Spc",
    "KC_LCTL": "Ctrl", "KC_RCTL": "Ctrl", "KC_LSFT": "Shift",
    "KC_RSFT": "Shift", "KC_LALT": "Alt", "KC_RALT": "Alt",
    "KC_LGUI": "Win", "KC_RGUI": "Win", "KC_CAPS": "Caps",
    "KC_HOME": "Home", "KC_END": "End", "KC_PGUP": "PgUp", "KC_PGDN": "PgDn",
    "KC_UP": "Up", "KC_DOWN": "Down", "KC_LEFT": "Left", "KC_RIGHT": "Rght",
    "QK_BOOT": "BOOT",
    "ALT_TAB": "A-Tab", "ALT_SHIFT_TAB": "AS-Tab",
    "CTRL_TAB": "C-Tab", "CTRL_SHIFT_TAB": "CS-Tab",
    "DICTATE": "Dict", "ENT_DICT": "EntDic",
    "LT(1, KC_SPACE)": "L1Spc",
}

MODS = {"LCTL": "C", "LSFT": "S", "LALT": "A", "LGUI": "G"}


def label(token):
    """Short name for one keymap entry, narrow enough for a cell."""
    token = token.strip()
    if token in LABELS:
        return LABELS[token]

    match = re.fullmatch(r"(LCTL|LSFT|LALT|LGUI)\((.+)\)", token)
    if match:
        return f"{MODS[match.group(1)]}-{label(match.group(2))}"

    match = re.fullmatch(r"LT\((\d+),\s*(.+)\)", token)
    if match:
        return f"L{match.group(1)}{label(match.group(2))}"

    if token.startswith("KC_"):
        return token[3:].capitalize() if len(token) > 4 else token[3:]
    return token


def split_cells(body):
    cells, depth, current = [], 0, ""
    for ch in body:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            cells.append(current)
            current = ""
        else:
            current += ch
    if current.strip():
        cells.append(current)
    return [c.strip() for c in cells if c.strip()]


def read_layers(source):
    layers = {}
    for index in range(4):
        block = re.search(rf"\[{index}\]\s*=\s*LAYOUT_split_3x6_3\((.*?)\n    \)",
                          source, re.S)
        if not block:
            continue
        cells = split_cells(re.sub(r"//[^\n]*", "", block.group(1)))
        layers[index] = [cells[r * 7:(r + 1) * 7] for r in range(10)]
    return layers


def row(cells, width):
    return "|" + "|".join(c.center(width) for c in cells) + "|"


def rule(count, width, left="+", mid="+", right="+"):
    return left + mid.join("-" * width for _ in range(count)) + right


def draw(grid, width=6):
    """One layer, left half 6 wide, right half 7 wide, thumbs underneath."""
    lines = []
    for r in range(4):
        left = [label(x) for x in grid[r][:6]]
        right = [label(x) for x in grid[r + 5][:7]]
        if r == 0:
            lines.append(rule(6, width) + "  " + rule(7, width))
        lines.append(row(left, width) + "  " + row(right, width))
        lines.append(rule(6, width) + "  " + rule(7, width))

    pad = " " * (3 * (width + 1))
    left_thumb = [label(x) for x in grid[4][2:5]]
    right_thumb = [label(x) for x in grid[9][1:4]]
    lines.append(pad + rule(3, width) + "  " + rule(3, width))
    lines.append(pad + row(left_thumb, width) + "  " + row(right_thumb, width))
    lines.append(pad + rule(3, width) + "  " + rule(3, width))
    return "\n".join(lines)


def render(source):
    layers = read_layers(source)
    out = [
        "`^` means the key falls through to the layer below, a blank cell means",
        "there is no key in that position.",
        "",
    ]
    for index, grid in sorted(layers.items()):
        if all(label(x) in ("", "^") for r in grid for x in r):
            continue  # nothing worth drawing
        out.append(f"**{LAYER_TITLES.get(index, f'Layer {index}')}**")
        out.append("")
        out.append("```")
        out.append(draw(grid))
        out.append("```")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def wsl_read(path):
    return subprocess.run(["wsl", "-d", "Ubuntu-24.04", "--", "cat", path],
                          capture_output=True, text=True).stdout


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true",
                        help="update README.md between the markers")
    parser.add_argument("--keymap", help="read this file instead of the repo copy")
    parser.add_argument("--readme", help="write this file instead of the repo copy")
    args = parser.parse_args()

    source = (Path(args.keymap).read_text(encoding="utf-8")
              if args.keymap else wsl_read(KEYMAP_WSL))
    if not source:
        raise SystemExit("Could not read keymap.c.")

    body = render(source)
    if not args.write:
        print(body)
        return

    readme_path = args.readme
    readme = (Path(readme_path).read_text(encoding="utf-8")
              if readme_path else wsl_read(README_WSL))
    if START not in readme or END not in readme:
        raise SystemExit(f"README is missing the markers:\n{START}\n{END}")

    updated = re.sub(f"{re.escape(START)}.*?{re.escape(END)}",
                     f"{START}\n\n{body}\n{END}", readme, flags=re.S)
    if readme_path:
        Path(readme_path).write_text(updated, encoding="utf-8", newline="\n")
    else:
        Path("rendered-readme.md").write_text(updated, encoding="utf-8", newline="\n")
        subprocess.run(["wsl", "-d", "Ubuntu-24.04", "--", "cp",
                        "/mnt/q/p/fiddly-firmware/rendered-readme.md", README_WSL],
                       check=True)
    print("README updated.")


if __name__ == "__main__":
    main()
